### PR TITLE
Fix typings for Command element find all methods

### LINKED ISSUE #159: getSpecAttribute type is incorrect for array context
In at least Leadfoot 2.2.x, `getSpecAttribute` is typed to always return a string, even when the context is an array. It should behave like other element methods (e.g., `getVisibleText`) and be typed to return an array when the context is an array (which it does).

### PR DESCRIPTION
**Pull request by edhager**
Fixes #159.

I modified the type declarations on the `Command` methods that operate on `Element` to correctly indicate when each method returns a `string` or `string[]`.

### CODE REVIEW

File: src/Command.ts [hunk 1]
```diff
@@ -1656,8 +1656,8 @@ export default class Command<T, P = any>
    * @returns The value of the attribute, or `null` if no such attribute
    * exists.
    */
-  getAttribute<T = any>(name: string) {
-    return this._callElementMethod<T>('getAttribute', name);
+  getAttribute(name: string) {
```
Comment (jason0x43) [inline src/Command.ts]: Can we leave the generic, but have it default to `StringResult<T>` instead of `any`? We don't actually need the generic, but removing out would cause problems for users that had been using it.
